# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'more_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_window(object):
    def setupUi(self, menu_window):
        menu_window.setObjectName("menu_window")
        menu_window.resize(200, 250)
        menu_window.setMinimumSize(QtCore.QSize(200, 250))
        menu_window.setMaximumSize(QtCore.QSize(200, 250))
        self.centralwidget = QtWidgets.QWidget(menu_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 200, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 20pt \"Times New Roman\";\n"
"background-color: rgb(85, 0, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 201, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.translator_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.translator_button.setEnabled(True)
        self.translator_button.setMinimumSize(QtCore.QSize(0, 40))
        self.translator_button.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font:  18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.translator_button.setObjectName("translator_button")
        self.verticalLayout.addWidget(self.translator_button)
        self.Article_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Article_button.setMinimumSize(QtCore.QSize(0, 40))
        self.Article_button.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font:  18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Article_button.setObjectName("Article_button")
        self.verticalLayout.addWidget(self.Article_button)
        self.Chat_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Chat_button.setMinimumSize(QtCore.QSize(0, 40))
        self.Chat_button.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font:  18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Chat_button.setObjectName("Chat_button")
        self.verticalLayout.addWidget(self.Chat_button)
        self.Exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Exit_button.setMinimumSize(QtCore.QSize(0, 40))
        self.Exit_button.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"font:  18pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.Exit_button.setObjectName("Exit_button")
        self.verticalLayout.addWidget(self.Exit_button)
        menu_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu_window)
        QtCore.QMetaObject.connectSlotsByName(menu_window)

    def retranslateUi(self, menu_window):
        _translate = QtCore.QCoreApplication.translate
        menu_window.setWindowTitle(_translate("menu_window", "More"))
        self.label.setText(_translate("menu_window", "Menu"))
        self.translator_button.setText(_translate("menu_window", "Translator"))
        self.Article_button.setText(_translate("menu_window", "Article"))
        self.Chat_button.setText(_translate("menu_window", "Chatbot"))
        self.Exit_button.setText(_translate("menu_window", "Exit"))
import Main_rc
