# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TranslateWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslateWindow(object):
    def setupUi(self, TranslateWindow):
        TranslateWindow.setObjectName("TranslateWindow")
        TranslateWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(TranslateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputText = QtWidgets.QTextEdit(self.centralwidget)
        self.InputText.setGeometry(QtCore.QRect(0, 50, 300, 201))
        self.InputText.setObjectName("InputText")
        self.TranslatedText = QtWidgets.QTextEdit(self.centralwidget)
        self.TranslatedText.setGeometry(QtCore.QRect(300, 50, 300, 201))
        self.TranslatedText.setReadOnly(True)
        self.TranslatedText.setObjectName("TranslatedText")
        self.ttEnglish = QtWidgets.QPushButton(self.centralwidget)
        self.ttEnglish.setGeometry(QtCore.QRect(0, 250, 301, 51))
        self.ttEnglish.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 8pt \"Georgia\";\n"
"background:rgb(255, 0, 68);")
        self.ttEnglish.setObjectName("ttEnglish")
        self.ttHindi = QtWidgets.QPushButton(self.centralwidget)
        self.ttHindi.setGeometry(QtCore.QRect(300, 250, 301, 51))
        self.ttHindi.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 8pt \"Georgia\";\n"
"background:rgb(255, 0, 68);")
        self.ttHindi.setObjectName("ttHindi")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: rgb(42, 77, 105);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 bold italic 19pt \"Times New Roman\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        TranslateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TranslateWindow)
        QtCore.QMetaObject.connectSlotsByName(TranslateWindow)

    def retranslateUi(self, TranslateWindow):
        _translate = QtCore.QCoreApplication.translate
        TranslateWindow.setWindowTitle(_translate("TranslateWindow", "MainWindow"))
        self.InputText.setPlaceholderText(_translate("TranslateWindow", "TYPE HERE"))
        self.ttEnglish.setText(_translate("TranslateWindow", "Translate To English"))
        self.ttHindi.setText(_translate("TranslateWindow", "Translate to Hindi"))
        self.label.setText(_translate("TranslateWindow", "TRANSLATOR"))
